config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :letters
  resources :greetings
  resources :bodies
  resources :closings

  get 'pages/about'

  root 'pages#home'

end

app/models/body.rb
class Body < ActiveRecord::Base
	belongs_to :user
	has_many :letters
end

app/models/closing.rb
class Closing < ActiveRecord::Base
	belongs_to :user
	has_many :letters
end

app/models/greeting.rb
class Greeting < ActiveRecord::Base
	belongs_to :user
	has_many :letters
end

app/models/letter.rb
class Letter < ActiveRecord::Base
	belongs_to :user
	belongs_to :greeting
	belongs_to :body
	belongs_to :closing
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :letters, dependent: :destroy
   has_many :greetings, dependent: :destroy
   has_many :bodies, dependent: :destroy
   has_many :closings, dependent: :destroy
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
      :password_confirmation, :name, :username) }

     devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
     :password_confirmation, :current_password, :name, :username) }
    end
    
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController

	def new
		@body = Body.new
	end

	def create
		@body = Body.new(body_params)
		@body.save!
		flash[:success] = "Body created successfully"
		@body = @body.id
		redirect_to new_letter_path
	end

	def destroy
		@body = Body.find params[:id]
  		@body.destroy!
  		redirect_to new_letter_path
	end

	private

	def body_params
  		params.require(:body).permit(:content, :name, :user_id)
	end

end

app/controllers/closings_controller.rb
class ClosingsController < ApplicationController

	def new
		@closing = Closing.new
	end

	def create
		@closing = Closing.new(closing_params)
		@closing.save!
		flash[:success] = "Closing created successfully"
		@closing= @closing.id
		redirect_to new_letter_path
	end

	def destroy
		@closing = Closing.find params[:id]
  		@closing.destroy!
  		redirect_to new_letter_path
	end

	private

	def closing_params
  		params.require(:closing).permit(:content, :name, :user_id)
  	end

end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController

	def new
		@greeting = Greeting.new
	end

	def create
		@greeting = Greeting.new(greeting_params)
		@greeting.save!
		flash[:success] = "Greeting created successfully"
		@greeting = @greeting.id
		redirect_to new_letter_path
	end

	def destroy
		@greeting = Greeting.find params[:id]
  		@greeting.destroy!
  		redirect_to new_letter_path
	end

	private

	def greeting_params
  		params.require(:greeting).permit(:content, :name, :user_id)
  	end

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

	before_action :authenticate_user!

  def index
  	@letters = Letter.all
  end

  def new
  	@letter = Letter.new
  end

  def create
  	@letter = Letter.new(letter_params)
  	@letter.user = current_user
		@letter.update(user: current_user)
	redirect_to action: :index
  end

  def show
  	@letter = Letter.find params[:id]
  end

  def destroy
  	@letter = Letter.find params[:id]
  	@letter.destroy!
  	redirect_to letters_path
  end

  private

  def letter_params
  	params.require(:letter).permit(:greeting_id, :body_id, :closing_id, :to_name, :user_id, :letter_type)
  end

  def load_and_render_show
	load_show_content
	redirect_to action: :show
  end

  def load_show_content
	@greeting = Greeting.all.user
	@body = Body.all.user
	@closing = Closing.all.user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/closings_helper.rb
module ClosingsHelper
end

app/helpers/greeting_helper.rb
module GreetingHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bodies/new.html.erb
<div class="container-fluid">
	<div class="panel panel-default">
		<h4><u>Create a new body</u></h4>

		<%= form_for Body.new, url: bodies_path do |f| %>

			<div class="form-group">
				<%= f.label :body_name %>
				<%= f.text_area :name, class: "form-inline" %>
			</div>
			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :content, class: "form-inline" %>
			</div>
			<%= f.submit "Create new body", class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/closings/new.html.erb
<div class="container-fluid">
	<div class="panel panel-default">
		<h4><u>Create a new closing</u></h4>

		<%= form_for Closing.new, url:  closings_path do |f| %>

			<div class="form-group">
				<%= f.label :closing_name %>
				<%= f.text_area :name, class: "form-inline" %>
			</div>
			<div class="form-group">
				<%= f.label :closing %>
				<%= f.text_area :content, class: "form-inline" %>
			</div>
			<%= f.submit "Create new closing", class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/greetings/new.html.erb
<div class="container-fluid">
	<div class="panel panel-default">
		<h4><u>Create a new greeting</u></h4>

		<%= form_for Greeting.new, url: greetings_path do |f| %>

			<div class="form-group">
				<%= f.label :greeting_name %>
				<%= f.text_area :name, class: "form-inline" %>
			</div>
			<div class="form-group">
				<%= f.label :greeting %>
				<%= f.text_area :content, class: "form-inline" %>
			</div>
			<%= f.submit "Create new greeting", class: "btn btn-default" %>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong><em>THANK YOU LETTER GENERATOR</em></strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "New Letter", new_letter_path %></li>
        <li><%= link_to "Saved Letters", letters_path %></li>
        <li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "About", pages_about_path %></li>
            <% if current_user.present? %>
              <li id="sign_out"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Original Thank You Letter Generator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/navbar' %>
<div class="container-fluid">
	<%= yield %>
	<br>
</div>

</body>
</html>

app/views/letters/index.html.erb
<div class="jumbotron jumbotron-primary" style="text-align: center">
	<h1><%= current_user.name %>'s saved letters</h1>
	<h4>(Be sure to proofread your letters!)</h4>
</div>

<% @letters.each do |letter| %>
	<div class="col-xs-12 col-md-7">
		<div class="panel panel-default">
			<div class="container-fluid">
				<%= letter.greeting.content.capitalize %> <%= letter.to_name %>,
				<br>
				<br>
				<%= letter.body.content.gsub(/([a-z])((?:[^.?!]|\.(?=[a-z]))*)/i) { $1.upcase + $2.rstrip } %>
				<br>
				<br>
				<%= letter.closing.content.capitalize %>,
				<br>
				<%= letter.user.name.capitalize %>
				<br>
			</div>
		</div>
		<%= link_to "delete this letter", letter, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
		<br>
		<br>
	</div>

<% end %>

app/views/letters/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 col-md-7">
			<div class="panel panel-primary">
				<div class="panel panel-heading">
					<h2>Create a new letter</h2>
				</div>
				<div class="panel panel-body">
					<div class="container-fluid">
					<%= form_for @letter, url: letters_path do |f| %>
					  	<div class="form-group">
							<%= f.label :letter_type %>
							<%= f.text_area :letter_type, class: "form-inline" %>
						</div>
						<div class="form-group">
							<%= f.label :to_name %>
							<%= f.text_area :to_name, class: "form-inline" %>
						</div>
					  	<div class="form-group">
					    		<%= f.collection_select :greeting_id, Greeting.all, :id, :content, {prompt: "choose a greeting"}, {class: "form-inline"} %>
					    		<%= link_to "No greetings? Click here to create a new greeting", new_greeting_path %>
				  		</div>
						<div class="form-group">
					    		<%= f.collection_select :body_id, Body.all, :id, :name, {prompt: "choose a body"}, {class: "form-inline"} %>
							<%= link_to "Create a new body", new_body_path %>  	
						</div>
						<div class="form-group">
							<%= f.collection_select :closing_id, Closing.all, :id, :name, {prompt: "choose a closing"}, {class: "form-inline"} %>
							<%= link_to "Create a new closing", new_closing_path %>
						</div>
						
						<%= f.submit "Create new letter", class: "btn btn-primary" %>
					<% end %>
				</div>
					<br>
				</div>
			</div>
		</div>
		<div class="col-xs-6 col-md-5">
			<div class="panel panel-info">
				<div class="panel panel-heading">
				<h3>Preview your letter</h3>
				</div>
				<div class="panel panel-body">
					<div class="greeting_preview">
					Greeting preview goes here
					</div>
					<div class="body_preview">
					Body preview goes here
					</div>
					<div class="closing_preview">
					Closing preview goes here
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
<h2>This app was designed by Jared Levin.</h2>
<h3>
	<ul>
		<li><a href="https://github.com/jarlev">Github</a></li>
		<li>Questions? <a href="mailto:jaredrlevin@gmail.com?Subject=Thank%20You%20Letter%20Generator%20Question" target="_top">Send me an email.</a></li>
	</ul>
</h3>

app/views/pages/home.html.erb
<div id="wrapper">
	<div class="jumbotron" style="text-align: center">
	<h1>The thank you letter generator</h1>
	<h3>An simple app designed to make your life easier. </h3>
	</div>
	<h3 style="text-align: center">Ever had to write a thank you letter for a gift or a job interview? It can be a frustrating process! </h3>
	<br>
	<img class="center" src="http://wallpaper.ultradownloads.com.br/276253_Papel-de-Parede-Meme-Jackie-Chan_1600x900.jpg" alt="frustrated_guy" width= "450px" height= "300px" />
	<br>
	<br>
	<h4 style="text-align: center">With this app, creating a well-written letter has never been easier!
	<br>
	Sign up <%=link_to "here", new_user_registration_path %> to get started!</h4>
	<br>
	<br>
</div>